odiseo_sylius_admin_banner:
    resource: |
        alias: odiseo_sylius_banner.banner
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: odiseo_sylius_banner
        permission: true
        vars:
            index:
                icon: trademark
    type: sylius.resource