odiseo_sylius_admin_banner_type:
    resource: |
        alias: odiseo_sylius_banner.banner_type
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: odiseo_sylius_banner_type
        permission: true
        vars:
            index:
                icon: trademark
    type: sylius.resource
