sylius_grid:
    grids:
        odiseo_sylius_banner_type:
            driver:
                name: doctrine/orm
                options:
                    class: "%odiseo_sylius_banner.model.banner_type.class%"
            sorting:
                createdAt: desc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                createdAt:
                    type: datetime
                    label: sylius.ui.creation_date
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
