services:
    odiseo_sylius_banner_plugin.event_listener.admin.menu_builder:
        class: Odiseo\SyliusBannerPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
