odiseo_sylius_banner_plugin_api_shop_banner:
    resource: |
        identifier: code
        alias: odiseo_sylius_banner_plugin.banner
        section: shop_api
        serialization_version: $version
        only: ['index', 'show']
        criteria:
            code: $code
    type: sylius.resource_api

odiseo_sylius_banner_plugin_shop_api_banner_by_taxon:
    path: /by-taxon/{code}
    methods: [GET]
    defaults:
        _controller: odiseo_sylius_banner_plugin.controller.banner:indexAction
        _sylius:
            serialization_version: $version
            section: shop_api
            repository:
                method: findByTaxon
                arguments:
                    - "expr:service('sylius.repository.taxon').findOneByCode($code)"
