Odiseo\SyliusBannerPlugin\Model\BannerType:
    type: mappedSuperclass
    table: odiseo_banner_type
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            unique: true
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        banners:
            targetEntity: Banner
            mappedBy: type
