Odiseo\SyliusBannerPlugin\Model\Banner:
    type: mappedSuperclass
    table: odiseo_banner
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            unique: true
        enabled:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        taxon:
            targetEntity: Sylius\Component\Taxonomy\Model\TaxonInterface
            joinColumn:
                name: taxon_id
                referenceColumnName: id
                onDelete: 'CASCADE'
    manyToMany:
        channels:
            targetEntity: Sylius\Component\Channel\Model\ChannelInterface
            inversedBy: banners
            joinTable:
                name: odiseo_banners_channels
                joinColumns:
                    banner_id:
                        referencedColumnName: id
                        onDelete: 'CASCADE'
                inverseJoinColumns:
                    channel_id:
                        referencedColumnName: id
