odiseo_sylius_banner_plugin_api_admin_banner:
    resource: |
        identifier: code
        alias: odiseo_sylius_banner_plugin.banner
        section: admin_api
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
